import amaranth as am
import amaranth.build

__all__ = ['SymbiYosysPlatform']

class SymbiYosysPlatform(am.build.TemplatedPlatform):
    device      = "symbiyosys"
    default_clk = "clk"
    default_rst = "rst"
    resources   = [
        am.build.Resource("clk", 0, am.build.Pins("clk", dir="i"), am.build.Clock(5e6)),
        am.build.Resource("rst", 0, am.build.Pins("rst", dir="i")),
    ]
    connectors  = []
    toolchain   = "yosys"

    file_templates = {
        **am.build.TemplatedPlatform.build_script_templates,
        "{{name}}.il": r"""
            # {{autogenerated}}
            {{emit_rtlil()}}
        """,
        "{{name}}.debug.v": r"""
            /* {{autogenerated}} */
            {{emit_debug_verilog()}}
        """,
        "{{name}}.sby": r"""
            # {{autogenerated}}
            [options]
            mode {{platform._mode}}
            depth {{platform._depth}}
            wait on
            multiclock on

            [engines]
            smtbmc

            [script]
            {% for file in platform.iter_files(".v") -%}
                read_verilog {{get_override("read_verilog_opts")|options}} ../../{{file}}
            {% endfor %}
            {% for file in platform.iter_files(".sv") -%}
                read_verilog {{get_override("read_verilog_opts")|options}} ../../{{file}}
            {% endfor %}
            {% for file in platform.iter_files(".il") -%}
                read_rtlil ../../{{file}}
            {% endfor %}
            read_rtlil ../../{{name}}.il
            {{get_override("script_after_read")|default("# (script_after_read placeholder)")}}
            prep
            {{platform._script_extra}}
        """,
    }

    required_tools = ["sby"]
    command_templates = [
        r"""
            {{invoke_tool("sby")}} -f -d sby
            {{get_override("sby_opts")|options}}
            {{name}}.sby
        """,
    ]

    def __init__(self, *, mode="bmc", depth=1):
        super().__init__()

        self._mode = mode
        self._depth = depth
        self._script_extra = ""

        if mode == "hybrid":
            self._script_extra = "setattr -unset init w:* a:amaranth.sample_reg %d"
            self._mode = "bmc"
